### ISSUE TITLE
Sign stopped showing train times

### ISSUE THREAD

**Issue by namtendo** [kenschneider18/rpi-metro-display#14]
My sign stopped showing the train times, only shows the top row with "LN CAR DEST MIN". I've had this happen a few times before but usually it sorts itself out within a few minutes automatically but it's been like this all day. Any idea what's up?

**Comment by kenschneider18** [comment]
Had to bump the e-mail on Monday but they finally got back to me and the issue appears resolved for me now. Hope it's working for you too!

**Comment by namtendo** [comment]
Yup, it's back up on my end too. Thanks!
