### ISSUE TITLE
Incidents showing in log file, but not on display

### ISSUE THREAD

**Issue by j-ea** [kenschneider18/rpi-metro-display#23]
First off, thank you for making this, and making and making it public. 

I'm on update/python3 branch. Everything works great, except I can see in the log there are incidents coming back from the API, but they don't display to the board.

Any idea what is going on here? I'm happy to continue troubleshooting, just hoping you could provide some direction. Thanks for your time.

**Comment by kenschneider18** [comment]
Did you ever get the incidents script to run on its own? From your earlier message it looked like that's what you were trying to do.

Without any logs from the display running it's difficult for me to say for sure. One thing I should highlight is that the way this displays incidents is slightly different than what you'd see on an actual metro sign. By default, incidents that don't effect the lines present at the station you're looking at are filtered out.

For example if your display is configured to pull times for `Foggy Bottom`, you'll only have incidents displayed for the orange, silver, and blue lines even if there's an incident on the red line.

The code that controls it is below:
https://github.com/kenschneider18/rpi-metro-display/blob/98b267939523405c9a42e48d7bb4c432de844467/rpi-metro-display.py#L100-L104

Assuming this is your issue and you want all incidents drawn, you could update the definition of `line_codes` to just be a string containing all the line codes. If you're up for it you could even modify the code make it an optional configuration so you can decide whether you want to display all incidents or just your line via `run.sh` and open a PR to add the feature.

Hope this helps!

**Comment by j-ea** [comment]
I did not get the script to run on its own. And correct, I was trying to do that, but based on incidents display correctly in the logs, I thought that might not be relevant.

Ah! Noted on the difference. That very well may have been it. I think the incidents were affecting different lines. I'm currently building a frame for the sign so everything is disconnected and I can't check at the moment, but I'll keep this thread up to date.

If that is the issue, I'm happy to submit a PR to make it a config option.

Thanks for your time and the speedy response.
